---
kind: pipeline
type: docker
name: default

steps:
- name: docker build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: frebib/mdns-repeater

- name: docker publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: frebib/mdns-repeater
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 73d2090c34d599f24f1acf9c69d71f62734b97a0bb307849685bb4e8306bfc1c

...
